package com.devbarboza.securerest.domain;
// Generated 5/06/2017 05:42:36 PM by Hibernate Tools 4.3.1



/**
 * Account generated by hbm2java
 */
public class Account  implements java.io.Serializable {


     private Long id;
     private String username;
     private String password;
     private String role;

    public Account() {
    }

    public Account(String username, String password, String role) {
       this.username = username;
       this.password = password;
       this.role = role;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getRole() {
        return this.role;
    }
    
    public void setRole(String role) {
        this.role = role;
    }
}


